module.exports = {
  extends: ['react', 'airbnb'],
  parser: '@typescript-eslint/parser',
  rules: {
    'no-shadow': 0,
    'no-param-reassign': 0,
    'no-underscore-dangle': 0,
    semi: ['error', 'never'],
    quotes: ['error', 'single'],
    'max-len': [
      0,
      {
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
      },
    ],
    'react/jsx-filename-extension': [0, { extensions: ['.ts', '.tsx'] }],
    'react/static-property-placement': 0,
    'react/prefer-stateless-function': 0,
    'react/button-has-type': 0,
    'react/jsx-props-no-spreading': 0,
    'react/react-in-jsx-scope': 0,
    'react/require-default-props': 0,
    'react/destructuring-assignment': 0,
    'react/no-danger': 0,
    'import/extensions': 0,
    'import/no-extraneous-dependencies': 0,
    'import/prefer-default-export': 0,
    'import/no-unresolved': [0, { ignore: ['antd-mobile'] }],
    'no-unused-vars': 1,
    'consistent-return': 0,
  },
}
