import validateAddressExtraFields from './api/address'
import { setChannelStoreType, uploadB2BFile } from './api/global'
import getBCToken from './api/login'
import getBCOrders from './api/order'
import {
  createBCCompanyUser,
  validateBCCompanyExtraFields,
} from './api/register'
import {
  createB2BAddress,
  createBcAddress,
  deleteB2BAddress,
  deleteBCCustomerAddress,
  getB2BAddress,
  getB2BAddressConfig,
  getB2BAddressExtraFields,
  getBCCustomerAddress,
  updateB2BAddress,
  updateBcAddress,
} from './graphql/address'
import {
  getAgentInfo,
  getB2BToken,
  getBcCurrencies,
  getCurrencies,
  getStorefrontConfig,
  getStorefrontConfigs,
  getTaxZoneRates,
  getUserCompany,
  superAdminBeginMasquerade,
  superAdminCompanies,
  superAdminEndMasquerade,
} from './graphql/global'
import {
  getB2BAllOrders,
  getB2BOrderDetails,
  getBCAllOrders,
  getBCOrderDetails,
  getBcOrderStatusType,
  getOrdersCreatedByUser,
  getOrderStatusType,
} from './graphql/orders'
import {
  B2BProductsBulkUploadCSV,
  BcProductsBulkUploadCSV,
  getB2BVariantInfoBySkus,
  getBcVariantInfoBySkus,
  guestProductsBulkUploadCSV,
  searchB2BProducts,
  searchBcProducts,
} from './graphql/product'
import {
  b2bQuoteCheckout,
  bcQuoteCheckout,
  createBCQuote,
  createQuote,
  exportB2BQuotePdf,
  exportBcQuotePdf,
  getB2BCustomerAddresses,
  getB2BQuoteDetail,
  getB2BQuotesList,
  getBCCustomerAddresses,
  getBcQuoteDetail,
  getBCQuotesList,
  getQuoteCreatedByUsers,
  quoteDetailAttachFileCreate,
  quoteDetailAttachFileDelete,
  updateB2BQuote,
  updateBCQuote,
} from './graphql/quote'
import {
  createB2BCompanyUser,
  getB2BAccountFormFields,
  getB2BCompanyUserInfo,
  getB2BCountries,
  getB2BLoginPageConfig,
  getB2BRegisterCustomFields,
  getB2BRegisterLogo,
  getBCForcePasswordReset,
  getBCStoreChannelId,
  storeB2BBasicInfo,
} from './graphql/register'
import {
  addProductToBcShoppingList,
  addProductToShoppingList,
  createB2BShoppingList,
  createBcShoppingList,
  deleteB2BShoppingList,
  deleteB2BShoppingListItem,
  deleteBcShoppingList,
  deleteBcShoppingListItem,
  duplicateB2BShoppingList,
  duplicateBcShoppingList,
  getB2BJuniorPlaceOrder,
  getB2BShoppingList,
  getB2BShoppingListDetails,
  getBcShoppingList,
  getBcShoppingListDetails,
  getShoppingListsCreatedByUser,
  updateB2BShoppingList,
  updateB2BShoppingListsItem,
  updateBcShoppingList,
  updateBcShoppingListsItem,
} from './graphql/shoppingList'
import {
  addOrUpdateUsers,
  checkUserBCEmail,
  checkUserEmail,
  deleteUsers,
  getUsers,
} from './graphql/users'

export {
  getB2BAccountSettings,
  getBCAccountSettings,
  updateB2BAccountSettings,
  updateBCAccountSettings,
} from './graphql/accountSetting'
export { getBcOrderedProducts, getOrderedProducts } from './graphql/quickorder'

export {
  addOrUpdateUsers,
  addProductToBcShoppingList,
  addProductToShoppingList,
  B2BProductsBulkUploadCSV,
  b2bQuoteCheckout,
  BcProductsBulkUploadCSV,
  bcQuoteCheckout,
  checkUserBCEmail,
  checkUserEmail,
  createB2BAddress,
  createB2BCompanyUser,
  createB2BShoppingList,
  createBcAddress,
  createBCCompanyUser,
  createBCQuote,
  createBcShoppingList,
  createQuote,
  deleteB2BAddress,
  deleteB2BShoppingList,
  deleteB2BShoppingListItem,
  deleteBCCustomerAddress,
  deleteBcShoppingList,
  deleteBcShoppingListItem,
  deleteUsers,
  duplicateB2BShoppingList,
  duplicateBcShoppingList,
  exportB2BQuotePdf,
  exportBcQuotePdf,
  getAgentInfo,
  getB2BAccountFormFields,
  getB2BAddress,
  getB2BAddressConfig,
  getB2BAddressExtraFields,
  getB2BAllOrders,
  getB2BCompanyUserInfo,
  getB2BCountries,
  getB2BCustomerAddresses,
  getB2BJuniorPlaceOrder,
  getB2BLoginPageConfig,
  getB2BOrderDetails,
  getB2BQuoteDetail,
  getB2BQuotesList,
  getB2BRegisterCustomFields,
  getB2BRegisterLogo,
  getB2BShoppingList,
  getB2BShoppingListDetails,
  getB2BToken,
  getB2BVariantInfoBySkus,
  getBCAllOrders,
  getBcCurrencies,
  getBCCustomerAddress,
  getBCCustomerAddresses,
  getBCForcePasswordReset,
  getBCOrderDetails,
  getBCOrders,
  getBcOrderStatusType,
  getBcQuoteDetail,
  getBCQuotesList,
  getBcShoppingList,
  getBcShoppingListDetails,
  getBCStoreChannelId,
  getBCToken,
  getBcVariantInfoBySkus,
  getCurrencies,
  getOrdersCreatedByUser,
  getOrderStatusType,
  getQuoteCreatedByUsers,
  getShoppingListsCreatedByUser,
  getStorefrontConfig,
  getStorefrontConfigs,
  getTaxZoneRates,
  getUserCompany,
  getUsers,
  guestProductsBulkUploadCSV,
  quoteDetailAttachFileCreate,
  quoteDetailAttachFileDelete,
  searchB2BProducts,
  searchBcProducts,
  setChannelStoreType,
  storeB2BBasicInfo,
  superAdminBeginMasquerade,
  superAdminCompanies,
  superAdminEndMasquerade,
  updateB2BAddress,
  updateB2BQuote,
  updateB2BShoppingList,
  updateB2BShoppingListsItem,
  updateBcAddress,
  updateBCQuote,
  updateBcShoppingList,
  updateBcShoppingListsItem,
  uploadB2BFile,
  validateAddressExtraFields,
  validateBCCompanyExtraFields,
}

export { default as getProxyInfo } from './api/proxy'
