import validateAddressExtraFields from './api/address';
import { setChannelStoreType, uploadB2BFile } from './api/global';
import getBCGraphqlToken from './api/login';
import getBCOrders from './api/order';
import {
  createBCCompanyUser,
  sendSubscribersState,
  validateBCCompanyExtraFields,
  validateBCCompanyUserExtraFields,
} from './api/register';
import {
  createB2BAddress,
  createBcAddress,
  deleteB2BAddress,
  deleteBCCustomerAddress,
  getB2BAddress,
  getB2BAddressConfig,
  getB2BAddressExtraFields,
  getBCCustomerAddress,
  updateB2BAddress,
  updateBcAddress,
} from './graphql/address';
import {
  getAgentInfo,
  getB2BToken,
  getBcCurrencies,
  getCompanyCreditConfig,
  getCurrencies,
  getStorefrontConfig,
  getStorefrontConfigs,
  getStorefrontDefaultLanguages,
  getTaxZoneRates,
  getUserCompany,
  superAdminBeginMasquerade,
  superAdminCompanies,
  superAdminEndMasquerade,
} from './graphql/global';
import {
  getB2BAllOrders,
  getB2BOrderDetails,
  getBCAllOrders,
  getBCOrderDetails,
  getBcOrderStatusType,
  getOrdersCreatedByUser,
  getOrderStatusType,
} from './graphql/orders';
import {
  B2BProductsBulkUploadCSV,
  BcProductsBulkUploadCSV,
  getB2BSkusInfo,
  getB2BVariantInfoBySkus,
  getBcVariantInfoBySkus,
  guestProductsBulkUploadCSV,
  searchB2BProducts,
  searchBcProducts,
} from './graphql/product';
import {
  b2bQuoteCheckout,
  bcQuoteCheckout,
  createBCQuote,
  createQuote,
  exportB2BQuotePdf,
  exportBcQuotePdf,
  getB2BCustomerAddresses,
  getB2BQuoteDetail,
  getB2BQuotesList,
  getBCCustomerAddresses,
  getBcQuoteDetail,
  getBCQuotesList,
  getBCStorefrontProductSettings,
  getQuoteCreatedByUsers,
  quoteDetailAttachFileCreate,
  quoteDetailAttachFileDelete,
  updateB2BQuote,
  updateBCQuote,
} from './graphql/quote';
import {
  createB2BCompanyUser,
  getB2BAccountFormFields,
  getB2BCompanyUserInfo,
  getB2BCountries,
  getB2BLoginPageConfig,
  getB2BRegisterCustomFields,
  getB2BRegisterLogo,
  getBCForcePasswordReset,
  getBCStoreChannelId,
  storeB2BBasicInfo,
} from './graphql/register';
import {
  addProductToBcShoppingList,
  addProductToShoppingList,
  createB2BShoppingList,
  createBcShoppingList,
  deleteB2BShoppingList,
  deleteB2BShoppingListItem,
  deleteBcShoppingList,
  deleteBcShoppingListItem,
  duplicateB2BShoppingList,
  duplicateBcShoppingList,
  getB2BJuniorPlaceOrder,
  getB2BShoppingList,
  getB2BShoppingListDetails,
  getBcShoppingList,
  getBcShoppingListDetails,
  getShoppingListsCreatedByUser,
  updateB2BShoppingList,
  updateB2BShoppingListsItem,
  updateBcShoppingList,
  updateBcShoppingListsItem,
} from './graphql/shoppingList';
import {
  addOrUpdateUsers,
  checkUserBCEmail,
  checkUserEmail,
  deleteUsers,
  getUsers,
  getUsersExtraFieldsInfo,
} from './graphql/users';

export {
  getB2BAccountSettings,
  getBCAccountSettings,
  updateB2BAccountSettings,
  updateBCAccountSettings,
} from './graphql/accountSetting';
export {
  exportInvoicesAsCSV,
  getInvoiceCheckoutUrl,
  getInvoiceDetail,
  getInvoiceList,
  getInvoicePaymentHistory,
  getInvoicePaymentInfo,
  getInvoiceStats,
  invoiceDownloadPDF,
} from './graphql/invoice';
export { getBcOrderedProducts, getOrderedProducts } from './graphql/quickorder';

export {
  addOrUpdateUsers,
  addProductToBcShoppingList,
  addProductToShoppingList,
  B2BProductsBulkUploadCSV,
  b2bQuoteCheckout,
  BcProductsBulkUploadCSV,
  bcQuoteCheckout,
  checkUserBCEmail,
  checkUserEmail,
  createB2BAddress,
  createB2BCompanyUser,
  createB2BShoppingList,
  createBcAddress,
  createBCCompanyUser,
  createBCQuote,
  createBcShoppingList,
  createQuote,
  deleteB2BAddress,
  deleteB2BShoppingList,
  deleteB2BShoppingListItem,
  deleteBCCustomerAddress,
  deleteBcShoppingList,
  deleteBcShoppingListItem,
  deleteUsers,
  duplicateB2BShoppingList,
  duplicateBcShoppingList,
  exportB2BQuotePdf,
  exportBcQuotePdf,
  getAgentInfo,
  getB2BAccountFormFields,
  getB2BAddress,
  getB2BAddressConfig,
  getB2BAddressExtraFields,
  getBCStorefrontProductSettings,
  getB2BAllOrders,
  getB2BCompanyUserInfo,
  getB2BCountries,
  getB2BCustomerAddresses,
  getB2BJuniorPlaceOrder,
  getB2BLoginPageConfig,
  getB2BOrderDetails,
  getB2BQuoteDetail,
  getB2BQuotesList,
  getB2BRegisterCustomFields,
  getB2BRegisterLogo,
  getB2BShoppingList,
  getB2BShoppingListDetails,
  getB2BSkusInfo,
  getB2BToken,
  getB2BVariantInfoBySkus,
  getBCAllOrders,
  getBcCurrencies,
  getBCCustomerAddress,
  getBCCustomerAddresses,
  getBCForcePasswordReset,
  getBCGraphqlToken,
  getBCOrderDetails,
  getBCOrders,
  getBcOrderStatusType,
  getBcQuoteDetail,
  getBCQuotesList,
  getBcShoppingList,
  getBcShoppingListDetails,
  getBCStoreChannelId,
  getBcVariantInfoBySkus,
  getCompanyCreditConfig,
  getCurrencies,
  getOrdersCreatedByUser,
  getOrderStatusType,
  getQuoteCreatedByUsers,
  getShoppingListsCreatedByUser,
  getStorefrontConfig,
  getStorefrontConfigs,
  getStorefrontDefaultLanguages,
  getTaxZoneRates,
  getUserCompany,
  getUsers,
  getUsersExtraFieldsInfo,
  guestProductsBulkUploadCSV,
  quoteDetailAttachFileCreate,
  quoteDetailAttachFileDelete,
  searchB2BProducts,
  searchBcProducts,
  sendSubscribersState,
  setChannelStoreType,
  storeB2BBasicInfo,
  superAdminBeginMasquerade,
  superAdminCompanies,
  superAdminEndMasquerade,
  updateB2BAddress,
  updateB2BQuote,
  updateB2BShoppingList,
  updateB2BShoppingListsItem,
  updateBcAddress,
  updateBCQuote,
  updateBcShoppingList,
  updateBcShoppingListsItem,
  uploadB2BFile,
  validateAddressExtraFields,
  validateBCCompanyExtraFields,
  validateBCCompanyUserExtraFields,
};

export { default as getProxyInfo } from './api/proxy';
export { default as getTranslation } from './api/translation';
