import validateAddressExtraFields from './api/address';
import { setChannelStoreType, uploadB2BFile, validateQuoteExtraFields } from './api/global';
import { validateBCCompanyExtraFields, validateBCCompanyUserExtraFields } from './api/register';
import {
  createB2BAddress,
  createBcAddress,
  deleteB2BAddress,
  deleteBCCustomerAddress,
  getB2BAddress,
  getB2BAddressConfig,
  getB2BAddressExtraFields,
  getBCCustomerAddress,
  updateB2BAddress,
  updateBcAddress,
} from './graphql/address';
import {
  endUserMasqueradingCompany,
  getAgentInfo,
  getB2BToken,
  getCompanyCreditConfig,
  getCompanySubsidiaries,
  getCurrencies,
  getProductPricing,
  getStoreConfigsSwitchStatus,
  getStorefrontConfig,
  getStorefrontConfigs,
  getStorefrontDefaultLanguages,
  getTaxZoneRates,
  getUserCompany,
  getUserMasqueradingCompany,
  startUserMasqueradingCompany,
  superAdminBeginMasquerade,
  superAdminCompanies,
  superAdminEndMasquerade,
} from './graphql/global';
import { getBCGraphqlToken } from './graphql/login';
import {
  getB2BAllOrders,
  getB2BOrderDetails,
  getBCAllOrders,
  getBCOrderDetails,
  getBcOrderStatusType,
  getOrdersCreatedByUser,
  getOrderStatusType,
} from './graphql/orders';
import {
  B2BProductsBulkUploadCSV,
  BcProductsBulkUploadCSV,
  getB2BSkusInfo,
  getB2BVariantInfoBySkus,
  getBcVariantInfoBySkus,
  guestProductsBulkUploadCSV,
  searchProducts,
} from './graphql/product';
import {
  createQuote,
  exportQuotePdf,
  getB2BCustomerAddresses,
  getB2BQuoteDetail,
  getB2BQuotesList,
  getBCCustomerAddresses,
  getBcQuoteDetail,
  getBCQuotesList,
  getBCStorefrontProductSettings,
  getQuoteCreatedByUsers,
  getQuoteExtraFieldsConfig,
  quoteCheckout,
  quoteDetailAttachFileCreate,
  quoteDetailAttachFileDelete,
  updateQuote,
} from './graphql/quote';
import {
  createB2BCompanyUser,
  createBCCompanyUser,
  getB2BAccountFormFields,
  getB2BCompanyUserInfo,
  getB2BCountries,
  getB2BLoginPageConfig,
  getB2BRegisterCustomFields,
  getB2BRegisterLogo,
  getBCForcePasswordReset,
  getBCStoreChannelId,
  sendSubscribersState,
  storeB2BBasicInfo,
} from './graphql/register';
import {
  getB2BCompanyRoleAndPermissionsDetails,
  getB2BPermissions,
  getB2BRoleList,
} from './graphql/roleAndPermissions';
import {
  addProductToBcShoppingList,
  addProductToShoppingList,
  createB2BShoppingList,
  createBcShoppingList,
  deleteB2BShoppingListItem,
  deleteBcShoppingListItem,
  getB2BJuniorPlaceOrder,
  getB2BShoppingList,
  getB2BShoppingListDetails,
  getBcShoppingList,
  getBcShoppingListDetails,
  getShoppingListsCreatedByUser,
  updateB2BShoppingList,
  updateB2BShoppingListsItem,
  updateBcShoppingList,
  updateBcShoppingListsItem,
} from './graphql/shoppingList';
import { checkUserBCEmail, checkUserEmail } from './graphql/users';

export {
  getB2BAccountSettings,
  getBCAccountSettings,
  updateB2BAccountSettings,
  updateBCAccountSettings,
} from './graphql/accountSetting';
export {
  exportInvoicesAsCSV,
  getInvoiceCheckoutUrl,
  getInvoiceDetail,
  getInvoiceList,
  getInvoicePaymentHistory,
  getInvoicePaymentInfo,
  getInvoiceStats,
  invoiceDownloadPDF,
} from './graphql/invoice';
export { getOrderedProducts } from './graphql/quickOrder';

export {
  addProductToBcShoppingList,
  addProductToShoppingList,
  B2BProductsBulkUploadCSV,
  quoteCheckout,
  BcProductsBulkUploadCSV,
  checkUserBCEmail,
  checkUserEmail,
  createB2BAddress,
  createB2BCompanyUser,
  createB2BShoppingList,
  createBcAddress,
  createBCCompanyUser,
  createBcShoppingList,
  createQuote,
  deleteB2BAddress,
  deleteB2BShoppingListItem,
  deleteBCCustomerAddress,
  deleteBcShoppingListItem,
  exportQuotePdf,
  getAgentInfo,
  getB2BAccountFormFields,
  getB2BAddress,
  getB2BAddressConfig,
  getB2BAddressExtraFields,
  getBCStorefrontProductSettings,
  getB2BAllOrders,
  getB2BCompanyUserInfo,
  getB2BCountries,
  getB2BCustomerAddresses,
  getB2BJuniorPlaceOrder,
  getB2BLoginPageConfig,
  getB2BOrderDetails,
  getB2BQuoteDetail,
  getB2BQuotesList,
  getB2BRegisterCustomFields,
  getB2BRegisterLogo,
  getB2BShoppingList,
  getB2BShoppingListDetails,
  getB2BSkusInfo,
  getB2BToken,
  getB2BCompanyRoleAndPermissionsDetails,
  getB2BPermissions,
  getB2BRoleList,
  getB2BVariantInfoBySkus,
  getBCAllOrders,
  getBCCustomerAddress,
  getBCCustomerAddresses,
  getBCForcePasswordReset,
  getBCGraphqlToken,
  getBCOrderDetails,
  getBcOrderStatusType,
  getBcQuoteDetail,
  getBCQuotesList,
  getBcShoppingList,
  getBcShoppingListDetails,
  getBCStoreChannelId,
  getCompanySubsidiaries,
  startUserMasqueradingCompany,
  endUserMasqueradingCompany,
  getUserMasqueradingCompany,
  getBcVariantInfoBySkus,
  getCompanyCreditConfig,
  getCurrencies,
  getOrdersCreatedByUser,
  getOrderStatusType,
  getQuoteCreatedByUsers,
  getQuoteExtraFieldsConfig,
  getShoppingListsCreatedByUser,
  getStorefrontConfig,
  getStorefrontConfigs,
  getStoreConfigsSwitchStatus,
  getStorefrontDefaultLanguages,
  getTaxZoneRates,
  getUserCompany,
  getProductPricing,
  guestProductsBulkUploadCSV,
  quoteDetailAttachFileCreate,
  quoteDetailAttachFileDelete,
  searchProducts,
  sendSubscribersState,
  setChannelStoreType,
  storeB2BBasicInfo,
  superAdminBeginMasquerade,
  superAdminCompanies,
  superAdminEndMasquerade,
  updateB2BAddress,
  updateQuote,
  updateB2BShoppingList,
  updateB2BShoppingListsItem,
  updateBcAddress,
  updateBcShoppingList,
  updateBcShoppingListsItem,
  uploadB2BFile,
  validateAddressExtraFields,
  validateBCCompanyExtraFields,
  validateBCCompanyUserExtraFields,
  validateQuoteExtraFields,
};

export { default as getTranslation } from './api/translation';
