name: 'Install Dependencies'
description: 'Install dependencies using Yarn and cache them'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NodeJS & Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
