name: Deploy to Staging

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
    secrets: inherit
