name: Deploy to Production - All Stores

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      build_command: build:production
    secrets: inherit
